// Generated by scripts/generate-contract.mjs. Do not edit by hand.

export const CARD_SYSTEMS = ["editorial", "swiss"] as const;
export const CARD_THEMES = ["ink_classic", "indigo_porcelain", "forest_ink", "kraft_paper", "dune", "midnight_ink", "ikb", "lemon", "lemon_green", "safety_orange"] as const;
export const CARD_LAYOUTS = ["feature", "field_note", "quote", "story_split", "media_quiet_zone", "document_excerpt", "metric_grid", "status_board", "evidence_top", "comparison", "steps", "alert"] as const;
export const CARD_TYPOGRAPHY = ["serif", "sans", "mono", "rounded"] as const;
export const CARD_DENSITIES = ["airy", "balanced", "compact"] as const;
export const CARD_MEDIA_PLACEMENTS = ["hero", "full_bleed", "split", "evidence", "inline"] as const;
export const CARD_CATALOG = {
  "schemaVersion": 1,
  "systems": [
    {
      "id": "editorial",
      "label": "Editorial",
      "description": "叙事、判断、总结与安静的图片表达。"
    },
    {
      "id": "swiss",
      "label": "Swiss",
      "description": "指标、步骤、对比、证据与告警。"
    }
  ],
  "themes": [
    {
      "id": "ink_classic",
      "system": "editorial",
      "label": "Ink Classic",
      "description": "通用默认、商业话题和稳定结论。",
      "ink": "#0A0A0B",
      "surface": "#F1EFEA",
      "accent": "#183B34"
    },
    {
      "id": "indigo_porcelain",
      "system": "editorial",
      "label": "Indigo Porcelain",
      "description": "技术、研究、AI 与方法分享。",
      "ink": "#0A1F3D",
      "surface": "#F1F3F5",
      "accent": "#315F88"
    },
    {
      "id": "forest_ink",
      "system": "editorial",
      "label": "Forest Ink",
      "description": "自然、可持续和非虚构叙事。",
      "ink": "#1A2E1F",
      "surface": "#F5F1E8",
      "accent": "#507555"
    },
    {
      "id": "kraft_paper",
      "system": "editorial",
      "label": "Kraft Paper",
      "description": "怀旧、人文、阅读与文学。",
      "ink": "#2A1E13",
      "surface": "#EEDFC7",
      "accent": "#9A6D3D"
    },
    {
      "id": "dune",
      "system": "editorial",
      "label": "Dune",
      "description": "艺术、设计、创意与时尚。",
      "ink": "#1F1A14",
      "surface": "#F0E6D2",
      "accent": "#B7894F"
    },
    {
      "id": "midnight_ink",
      "system": "editorial",
      "label": "Midnight Ink",
      "description": "夜景、影调封面与深色题材。",
      "ink": "#ECE2CF",
      "surface": "#0E0D0C",
      "accent": "#D4A04A"
    },
    {
      "id": "ikb",
      "system": "swiss",
      "label": "IKB",
      "description": "商业发布、AI 产品和方法论。",
      "ink": "#10120F",
      "surface": "#F2F2ED",
      "accent": "#002FA7"
    },
    {
      "id": "lemon",
      "system": "swiss",
      "label": "Lemon",
      "description": "年轻、运动、零售与消费品。",
      "ink": "#10120F",
      "surface": "#F2F2ED",
      "accent": "#FFD500"
    },
    {
      "id": "lemon_green",
      "system": "swiss",
      "label": "Lemon Green",
      "description": "Zimlo 默认、生态、健康与完成结果。",
      "ink": "#10120F",
      "surface": "#F2F2ED",
      "accent": "#C5E803"
    },
    {
      "id": "safety_orange",
      "system": "swiss",
      "label": "Safety Orange",
      "description": "告警、失败、新闻与工业场景。",
      "ink": "#10120F",
      "surface": "#F2F2ED",
      "accent": "#FF6B35"
    }
  ],
  "layouts": [
    {
      "id": "feature",
      "system": "editorial",
      "label": "Feature",
      "description": "大标题与叙事摘要，适合纯文字结论。",
      "requires": []
    },
    {
      "id": "field_note",
      "system": "editorial",
      "label": "Field Note",
      "description": "结论、事实台账和验证信息。",
      "requires": []
    },
    {
      "id": "quote",
      "system": "editorial",
      "label": "Quote",
      "description": "以引用或核心判断为视觉中心。",
      "requires": [
        "quote"
      ]
    },
    {
      "id": "story_split",
      "system": "editorial",
      "label": "Story Split",
      "description": "叙事正文与结构化事实分栏。",
      "requires": []
    },
    {
      "id": "media_quiet_zone",
      "system": "editorial",
      "label": "Media Quiet Zone",
      "description": "照片主导，在安静区放置标题。",
      "requires": [
        "media"
      ]
    },
    {
      "id": "document_excerpt",
      "system": "editorial",
      "label": "Document Excerpt",
      "description": "文档摘要与可阅读摘录。",
      "requires": [
        "document"
      ]
    },
    {
      "id": "metric_grid",
      "system": "swiss",
      "label": "Metric Grid",
      "description": "突出一组关键指标。",
      "requires": [
        "metric"
      ]
    },
    {
      "id": "status_board",
      "system": "swiss",
      "label": "Status Board",
      "description": "状态、结果和验证事实的硬网格。",
      "requires": []
    },
    {
      "id": "evidence_top",
      "system": "swiss",
      "label": "Evidence Top",
      "description": "顶部证据图与底部结构化结论。",
      "requires": [
        "media"
      ]
    },
    {
      "id": "comparison",
      "system": "swiss",
      "label": "Comparison",
      "description": "左右对比两个方案或状态。",
      "requires": [
        "comparison"
      ]
    },
    {
      "id": "steps",
      "system": "swiss",
      "label": "Steps",
      "description": "按顺序展示过程与下一步。",
      "requires": [
        "step"
      ]
    },
    {
      "id": "alert",
      "system": "swiss",
      "label": "Alert",
      "description": "需要注意、失败或高优先级判断。",
      "requires": [
        "attention"
      ]
    }
  ],
  "typography": [
    {
      "id": "serif",
      "label": "Serif",
      "description": "编辑感衬线字体。"
    },
    {
      "id": "sans",
      "label": "Sans",
      "description": "清晰克制的无衬线字体。"
    },
    {
      "id": "mono",
      "label": "Mono",
      "description": "技术、证据和编号感。"
    },
    {
      "id": "rounded",
      "label": "Rounded",
      "description": "更轻松、更具产品感。"
    }
  ],
  "densities": [
    {
      "id": "airy",
      "label": "Airy",
      "description": "少量内容和更大留白。"
    },
    {
      "id": "balanced",
      "label": "Balanced",
      "description": "默认阅读密度。"
    },
    {
      "id": "compact",
      "label": "Compact",
      "description": "较多事实和指标。"
    }
  ],
  "mediaPlacements": [
    {
      "id": "hero",
      "label": "Hero",
      "description": "顶部主视觉。"
    },
    {
      "id": "full_bleed",
      "label": "Full Bleed",
      "description": "图片满铺并叠加高对比文字。"
    },
    {
      "id": "split",
      "label": "Split",
      "description": "图片与文字分栏。"
    },
    {
      "id": "evidence",
      "label": "Evidence",
      "description": "图片作为有边界的证据区。"
    },
    {
      "id": "inline",
      "label": "Inline",
      "description": "文档或媒体嵌入正文流。"
    }
  ]
} as const;
