// Generated by scripts/generate-contract.mjs. Do not edit by hand.
enum ZimloContract {
    static let productVersion = "0.2.1"
    static let protocolVersion = 5
}

enum ZimloCardCatalog {
    static let systems = ["editorial", "swiss"]
    static let themes = ["ink_classic", "indigo_porcelain", "forest_ink", "kraft_paper", "dune", "midnight_ink", "ikb", "lemon", "lemon_green", "safety_orange"]
    static let layouts = ["feature", "field_note", "quote", "story_split", "media_quiet_zone", "document_excerpt", "metric_grid", "status_board", "evidence_top", "comparison", "steps", "alert"]
    static let typography = ["serif", "sans", "mono", "rounded"]
    static let densities = ["airy", "balanced", "compact"]
    static let mediaPlacements = ["hero", "full_bleed", "split", "evidence", "inline"]
    static let themeSystems: [String: String] = [
        "ink_classic": "editorial",
        "indigo_porcelain": "editorial",
        "forest_ink": "editorial",
        "kraft_paper": "editorial",
        "dune": "editorial",
        "midnight_ink": "editorial",
        "ikb": "swiss",
        "lemon": "swiss",
        "lemon_green": "swiss",
        "safety_orange": "swiss"
    ]
    static let layoutSystems: [String: String] = [
        "feature": "editorial",
        "field_note": "editorial",
        "quote": "editorial",
        "story_split": "editorial",
        "media_quiet_zone": "editorial",
        "document_excerpt": "editorial",
        "metric_grid": "swiss",
        "status_board": "swiss",
        "evidence_top": "swiss",
        "comparison": "swiss",
        "steps": "swiss",
        "alert": "swiss"
    ]
    static let themeInk: [String: String] = [
        "ink_classic": "#0A0A0B",
        "indigo_porcelain": "#0A1F3D",
        "forest_ink": "#1A2E1F",
        "kraft_paper": "#2A1E13",
        "dune": "#1F1A14",
        "midnight_ink": "#ECE2CF",
        "ikb": "#10120F",
        "lemon": "#10120F",
        "lemon_green": "#10120F",
        "safety_orange": "#10120F"
    ]
    static let themeSurface: [String: String] = [
        "ink_classic": "#F1EFEA",
        "indigo_porcelain": "#F1F3F5",
        "forest_ink": "#F5F1E8",
        "kraft_paper": "#EEDFC7",
        "dune": "#F0E6D2",
        "midnight_ink": "#0E0D0C",
        "ikb": "#F2F2ED",
        "lemon": "#F2F2ED",
        "lemon_green": "#F2F2ED",
        "safety_orange": "#F2F2ED"
    ]
    static let themeAccent: [String: String] = [
        "ink_classic": "#183B34",
        "indigo_porcelain": "#315F88",
        "forest_ink": "#507555",
        "kraft_paper": "#9A6D3D",
        "dune": "#B7894F",
        "midnight_ink": "#D4A04A",
        "ikb": "#002FA7",
        "lemon": "#FFD500",
        "lemon_green": "#C5E803",
        "safety_orange": "#FF6B35"
    ]
}
